
anyhow:
	cargo run --bin anyhow

thiserror:
	cargo +nightly run --bin thiserror

snafu:
	cargo run --bin snafu

thiserror-client:
	cargo run --bin thiserror-client

snafu-client:
	cargo run --bin snafu-client
